"use client";

import { useEffect, useMemo, useState } from "react";
import { ArrowDownLeft, ArrowRight, ArrowUpRight, BookOpen, Check, ChevronDown, ChevronLeft, ChevronRight, CircleAlert, Clock3, Download, FileText, Landmark, Layers3, Plus, Search, SlidersHorizontal, Target, Wallet, X } from "lucide-react";
import type { AccountCategory, Snapshot, TransactionItem } from "@/lib/types";
import { EmptyState, formatDate, formatDateTime, formatMoney, PageIntro, reportUrl, StatusPill, TypeIcon, typeLabel } from "@/components/finance-ui";

type Action = (payload: Record<string, unknown>) => Promise<boolean>;

export function TransactionsView({ data, searchTerm, onNew, onAction, working }: { data: Snapshot; searchTerm: string; onNew: () => void; onAction: Action; working: boolean }) {
  const [search, setSearch] = useState(searchTerm);
  const [typeFilter, setTypeFilter] = useState("all");
  const [statusFilter, setStatusFilter] = useState("all");
  const [page, setPage] = useState(1);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [confirmReverse, setConfirmReverse] = useState(false);
  useEffect(() => { setSearch(searchTerm); setPage(1); }, [searchTerm]);
  const selected = data.transactions.find((txn) => txn.id === selectedId);
  const filtered = useMemo(() => data.transactions.filter((txn) => {
    const needle = search.toLowerCase();
    return (typeFilter === "all" || txn.type === typeFilter) && (statusFilter === "all" || txn.status === statusFilter) &&
      (!needle || [txn.reference, txn.description, txn.payee, txn.type].some((field) => field.toLowerCase().includes(needle)));
  }), [data.transactions, search, typeFilter, statusFilter]);
  const pageSize = 10;
  const totalPages = Math.max(1, Math.ceil(filtered.length / pageSize));
  const visible = filtered.slice((page - 1) * pageSize, page * pageSize);
  const from = `${data.fiscalYear}-01-01`;
  const to = new Date().toISOString().slice(0, 10);

  return <div>
    <PageIntro eyebrow="LEDGER  /  TRANSACTIONS" title="Transactions" subtitle="Review and manage every financial movement across the centre." actions={<><a className="btn btn-secondary" href={reportUrl("transactions", from, to)}><Download size={17} /> Export CSV</a>{data.user.role !== "viewer" && <button className="btn btn-primary" onClick={onNew}><Plus size={18} /> New transaction</button>}</>} />
    <div className="mini-summary-grid"><div className="mini-summary"><span className="mini-summary-icon blue"><Layers3 size={19} /></span><div><strong>{data.dashboard.transactionCount}</strong><span>Posted this year</span></div></div><div className="mini-summary"><span className="mini-summary-icon green"><ArrowDownLeft size={19} /></span><div><strong>{formatMoney(data.dashboard.income)}</strong><span>Income recorded</span></div></div><div className="mini-summary"><span className="mini-summary-icon orange"><ArrowUpRight size={19} /></span><div><strong>{formatMoney(data.dashboard.expenses)}</strong><span>Expenses recorded</span></div></div><div className="mini-summary"><span className="mini-summary-icon purple"><Clock3 size={19} /></span><div><strong>{data.dashboard.draftCount}</strong><span>Awaiting posting</span></div></div></div>
    <section className="panel table-panel"><div className="table-toolbar"><div className="table-toolbar-heading"><h2>All transactions</h2><span className="count-badge">{filtered.length}</span></div><div className="table-filters"><div className="search-field"><Search size={17} /><input aria-label="Search transactions" placeholder="Search transactions..." value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} /></div><div className="select-wrap"><SlidersHorizontal size={15} /><select aria-label="Filter by type" value={typeFilter} onChange={(event) => { setTypeFilter(event.target.value); setPage(1); }}><option value="all">All types</option><option value="income">Income</option><option value="expense">Expense</option><option value="transfer">Transfer</option><option value="journal">Journal</option><option value="reversal">Reversal</option></select><ChevronDown size={14} /></div><div className="select-wrap"><select aria-label="Filter by status" value={statusFilter} onChange={(event) => { setStatusFilter(event.target.value); setPage(1); }}><option value="all">All statuses</option><option value="posted">Posted</option><option value="draft">Draft</option><option value="reversed">Reversed</option></select><ChevronDown size={14} /></div></div></div>
      <div className="table-scroll"><table className="data-table ledger-table"><thead><tr><th>Reference / Description</th><th>Type</th><th>Date</th><th>Payee / Source</th><th className="align-right">Amount</th><th>Status</th><th aria-label="Details" /></tr></thead><tbody>{visible.map((txn) => <tr key={txn.id} className="clickable-row" onClick={() => { setSelectedId(txn.id); setConfirmReverse(false); }}><td><div className="transaction-cell"><span className={`type-icon type-${txn.type}`}><TypeIcon type={txn.type} /></span><span><strong>{txn.description}</strong><small>{txn.reference}</small></span></div></td><td><span className="type-text">{typeLabel(txn.type)}</span></td><td className="muted-cell">{formatDate(txn.date)}</td><td className="muted-cell truncate-cell">{txn.payee || "—"}</td><td className={`align-right amount-cell ${txn.type === "income" ? "income-text" : txn.type === "expense" ? "expense-text" : ""}`}>{txn.type === "income" ? "+" : txn.type === "expense" ? "−" : ""}{formatMoney(txn.amount)}</td><td><StatusPill status={txn.status} /></td><td><ChevronRight size={17} className="row-chevron" /></td></tr>)}</tbody></table>{!visible.length && <EmptyState icon={<FileText size={25} />} title="No transactions found" description="Try a different search or filter, or record a new transaction." />}</div>
      <div className="table-pagination"><span>Showing {filtered.length ? (page - 1) * pageSize + 1 : 0}–{Math.min(page * pageSize, filtered.length)} of {filtered.length} entries</span><div><button disabled={page === 1} onClick={() => setPage(page - 1)} aria-label="Previous page"><ChevronLeft size={17} /></button><span>{page} / {totalPages}</span><button disabled={page >= totalPages} onClick={() => setPage(page + 1)} aria-label="Next page"><ChevronRight size={17} /></button></div></div>
    </section>
    {selected && <div className="drawer-layer"><div className="drawer-scrim" onClick={() => setSelectedId(null)} /><aside className="detail-drawer" role="dialog" aria-modal="true" aria-label="Transaction details"><div className="drawer-header"><div><span>TRANSACTION DETAILS</span><h2>{selected.reference}</h2></div><button className="icon-close" aria-label="Close details" onClick={() => setSelectedId(null)}><X size={20} /></button></div><div className="drawer-body"><div className={`drawer-amount drawer-amount-${selected.type}`}><span>{typeLabel(selected.type)} transaction</span><strong>{selected.type === "income" ? "+" : selected.type === "expense" ? "−" : ""}{formatMoney(selected.amount, 2)}</strong><StatusPill status={selected.status} /></div><h3 className="drawer-description">{selected.description}</h3><div className="detail-list"><div><span>Date</span><strong>{formatDate(selected.date)}</strong></div><div><span>Payee / source</span><strong>{selected.payee || "Not specified"}</strong></div><div><span>Payment method</span><strong>{selected.paymentMethod}</strong></div><div><span>Recorded by</span><strong>{selected.createdBy}</strong></div><div><span>Created</span><strong>{formatDateTime(selected.createdAt)}</strong></div></div><div className="drawer-section-title"><BookOpen size={17} /> Journal entry</div><p className="drawer-help">Double-entry record for this transaction.</p><div className="journal-preview"><div className="journal-head"><span>ACCOUNT</span><span>DEBIT</span><span>CREDIT</span></div>{selected.lines.map((line) => <div className="journal-row" key={line.id}><span><strong>{line.accountCode}</strong> {line.accountName}</span><span>{line.debit ? formatMoney(line.debit, 2) : "—"}</span><span>{line.credit ? formatMoney(line.credit, 2) : "—"}</span></div>)}<div className="journal-row journal-total"><span>Total</span><span>{formatMoney(selected.lines.reduce((sum, line) => sum + line.debit, 0), 2)}</span><span>{formatMoney(selected.lines.reduce((sum, line) => sum + line.credit, 0), 2)}</span></div></div><div className="balanced-note"><Check size={16} /> Debits and credits are balanced</div>{selected.status === "reversed" && <div className="reversal-note"><CircleAlert size={17} /> This entry was reversed by a compensating journal. The original record remains in the audit trail.</div>}</div>
      {data.user.role !== "viewer" && (selected.status === "draft" || selected.status === "posted") && <div className="drawer-footer">{selected.status === "draft" ? <button className="btn btn-primary full-width" disabled={working} onClick={async () => { if (await onAction({ action: "postTransaction", id: selected.id })) setSelectedId(null); }}><Check size={17} /> {working ? "Posting..." : "Approve & post transaction"}</button> : confirmReverse ? <div className="reverse-confirm"><p>Reverse this posted entry? A balancing journal will be created; the original cannot be deleted.</p><div><button className="btn btn-secondary" onClick={() => setConfirmReverse(false)}>Cancel</button><button className="btn btn-danger" disabled={working} onClick={async () => { if (await onAction({ action: "reverseTransaction", id: selected.id })) setSelectedId(null); }}>Confirm reversal</button></div></div> : <button className="btn btn-secondary full-width" onClick={() => setConfirmReverse(true)}>Reverse transaction</button>}</div>}</aside></div>}
  </div>;
}

const categoryNames: Record<AccountCategory, string> = { asset: "Assets", liability: "Liabilities", equity: "Equity", income: "Income", expense: "Expenses" };

export function AccountsView({ data, onAdd }: { data: Snapshot; onAdd: () => void }) {
  const [search, setSearch] = useState("");
  const [category, setCategory] = useState("all");
  const filtered = data.accounts.filter((item) => (category === "all" || item.category === category) && (!search || `${item.code} ${item.name} ${item.description}`.toLowerCase().includes(search.toLowerCase())));
  const sums = (kind: AccountCategory) => data.accounts.filter((item) => item.category === kind).reduce((sum, item) => sum + item.balance, 0);
  return <div><PageIntro eyebrow="LEDGER  /  CHART OF ACCOUNTS" title="Chart of accounts" subtitle="A structured view of every account in UPEC’s financial ledger." actions={data.user.role === "admin" && <button className="btn btn-primary" onClick={onAdd}><Plus size={18} /> Add account</button>} />
    <div className="account-banner"><div className="account-banner-icon"><Landmark size={22} /></div><div><strong>University of Port Harcourt Entrepreneurial Centre</strong><span>Institutional chart of accounts · Accounting / Vote Head 520</span></div><span className="account-banner-tag">{data.accounts.length} ACCOUNTS</span></div>
    <div className="account-summary-grid"><div className="account-summary"><span className="account-summary-icon blue"><Wallet size={20} /></span><span>Assets</span><strong>{formatMoney(sums("asset"))}</strong></div><div className="account-summary"><span className="account-summary-icon purple"><Layers3 size={20} /></span><span>Liabilities</span><strong>{formatMoney(sums("liability"))}</strong></div><div className="account-summary"><span className="account-summary-icon green"><ArrowDownLeft size={20} /></span><span>Income</span><strong>{formatMoney(sums("income"))}</strong></div><div className="account-summary"><span className="account-summary-icon orange"><ArrowUpRight size={20} /></span><span>Expenses</span><strong>{formatMoney(sums("expense"))}</strong></div></div>
    <section className="panel table-panel"><div className="table-toolbar"><div className="table-toolbar-heading"><h2>Account directory</h2><span className="count-badge">{filtered.length}</span></div><div className="search-field"><Search size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search accounts..." aria-label="Search accounts" /></div></div><div className="filter-tabs">{["all", "asset", "liability", "equity", "income", "expense"].map((item) => <button key={item} className={category === item ? "active" : ""} onClick={() => setCategory(item)}>{item === "all" ? "All accounts" : categoryNames[item as AccountCategory]}</button>)}</div><div className="table-scroll"><table className="data-table account-table"><thead><tr><th>Code</th><th>Account name</th><th>Category</th><th>Description</th><th className="align-right">Balance</th><th>Status</th></tr></thead><tbody>{filtered.map((item) => <tr key={item.id}><td><span className="account-code">{item.code}</span></td><td><strong>{item.name}</strong></td><td><span className={`category-pill category-${item.category}`}>{categoryNames[item.category]}</span></td><td className="muted-cell truncate-cell">{item.description || "—"}</td><td className="align-right amount-cell">{formatMoney(item.balance, 2)}</td><td><span className="active-status"><span />{item.isActive ? "Active" : "Inactive"}</span></td></tr>)}</tbody></table>{!filtered.length && <EmptyState icon={<BookOpen size={25} />} title="No accounts found" description="Try another search or category filter." />}</div></section>
  </div>;
}

export function BudgetsView({ data, onEdit }: { data: Snapshot; onEdit: (accountId?: string) => void }) {
  const { dashboard } = data;
  const available = dashboard.allocated - dashboard.spent;
  const usage = dashboard.allocated ? dashboard.spent / dashboard.allocated * 100 : 0;
  const atRisk = data.budgets.filter((item) => item.utilization >= 85).length;
  return <div><PageIntro eyebrow={`PLANNING  /  FY ${data.fiscalYear}`} title="Budget monitoring" subtitle="Plan with purpose. Track approved allocations against actual spending." actions={data.user.role === "admin" && <button className="btn btn-primary" onClick={() => onEdit()}><Plus size={18} /> Manage allocation</button>} />
    <div className="budget-hero"><div className="budget-hero-copy"><span>VOTE HEAD 520 · FINANCIAL YEAR {data.fiscalYear}</span><h2>Stay ahead of every allocation.</h2><p>Real-time visibility into how UPEC funds are being used across operational priorities.</p></div><div className="budget-hero-stat"><span>Overall utilization</span><strong>{usage.toFixed(1)}%</strong><div><span style={{ width: `${Math.min(usage, 100)}%` }} /></div></div></div>
    <div className="budget-stat-grid"><div className="budget-stat"><span className="budget-stat-icon blue"><Target size={21} /></span><span>Approved budget</span><strong>{formatMoney(dashboard.allocated)}</strong><small>Across {data.budgets.length} expense lines</small></div><div className="budget-stat"><span className="budget-stat-icon orange"><ArrowUpRight size={21} /></span><span>Actual expenditure</span><strong>{formatMoney(dashboard.spent)}</strong><small>Posted to the ledger</small></div><div className="budget-stat"><span className="budget-stat-icon green"><Wallet size={21} /></span><span>Remaining balance</span><strong className={available < 0 ? "text-danger" : ""}>{available < 0 ? "−" : ""}{formatMoney(available)}</strong><small>Available for the rest of the year</small></div><div className="budget-stat"><span className="budget-stat-icon purple"><CircleAlert size={21} /></span><span>Lines to watch</span><strong>{atRisk}</strong><small>At or above 85% utilisation</small></div></div>
    <section className="panel budget-lines-panel"><div className="panel-heading"><div><h2>Allocation by expense head</h2><p>Approved budget and actual expenditure, updated as entries are posted</p></div><span className="panel-tag">FY {data.fiscalYear}</span></div><div className="budget-lines">{data.budgets.map((item) => <div className="budget-line" key={item.accountId}><div className="budget-line-main"><div className="budget-line-icon"><Target size={19} /></div><div className="budget-line-info"><div className="budget-line-title"><strong>{item.accountName}</strong><span>{item.accountCode}</span></div><div className="budget-line-sub">{formatMoney(item.spent)} spent of {formatMoney(item.allocated)} allocated</div><div className="budget-bar"><span className={item.utilization > 100 ? "over" : item.utilization >= 85 ? "warning" : ""} style={{ width: `${Math.min(Math.max(item.utilization, 0), 100)}%` }} /></div></div></div><div className="budget-line-end"><strong className={item.utilization > 100 ? "text-danger" : item.utilization >= 85 ? "text-warning" : ""}>{item.utilization.toFixed(1)}%</strong><small>{item.remaining < 0 ? `${formatMoney(item.remaining)} over` : `${formatMoney(item.remaining)} left`}</small></div>{data.user.role === "admin" && <button className="budget-edit" onClick={() => onEdit(item.accountId)}>Edit <ArrowRight size={14} /></button>}</div>)}</div></section>
    <div className="budget-note"><CircleAlert size={18} /><span><strong>How this works:</strong> Actuals are calculated from posted double-entry journal lines. Reversals offset the original entry, and drafts do not affect budgets.</span></div>
  </div>;
}
